// ============================================================
// Game Constants
// ============================================================

export const SCREEN = {
  DESIGN_WIDTH: 375,
  DESIGN_HEIGHT: 667,
} as const;

export const GAME = {
  FPS: 60,
  FIXED_TIMESTEP: 1 / 60,
  MAX_DELTA: 0.1,
  MAX_IDLE_HOURS: 8,
  COIN_GENERATION_BASE: 1,
  WEATHER_POLL_INTERVAL_MS: 15 * 60 * 1000,
  SPRITE_SPAWN_INTERVAL_MS: 30 * 60 * 1000,
  STEP_TO_WIND_RATIO: 0.01,
  GIFT_EXPIRY_HOURS: 48,
  MAX_PLANT_SLOTS: 9,
  MAX_WINDMILL_LEVEL: 10,
  MAX_SPRITE_LEVEL: 30,
  GROWTH_WEATHER_MULTIPLIER: {
    sunny: 1.0,
    cloudy: 0.9,
    rainy: 1.3,
    snowy: 0.7,
    thunderstorm: 0.5,
    foggy: 0.8,
    windy: 1.1,
  },
} as const;

export const LAYERS = {
  BACKGROUND: 0,
  ENTITIES: 10,
  EFFECTS: 20,
  UI: 30,
  OVERLAY: 40,
} as const;

export const COLORS = {
  // Island
  ISLAND_BASE: '#8CC6A5',
  ISLAND_GRASS: '#7ECBA1',
  ISLAND_GRASS_HIGHLIGHT: '#A8DCC0',
  ISLAND_DIRT: '#C4A882',
  ISLAND_DIRT_DARK: '#A88B6A',
  ISLAND_SHADOW: 'rgba(26, 39, 56, 0.12)',

  // Water
  WATER: '#7EB5D6',
  WATER_LIGHT: '#A8D4EC',
  WATER_SHIMMER: '#D6EAF5',

  // Clouds
  CLOUD_WHITE: '#FAFBFD',
  CLOUD_WHITE_SHADOW: '#E1E6EE',
  CLOUD_RAIN: '#90A4AE',
  CLOUD_RAIN_SHADOW: '#78909C',
  CLOUD_GIFT: '#F2C57C',
  CLOUD_GIFT_RIBBON: '#E5A84D',

  // Weather effects
  RAIN: '#A8D4EC',
  RAIN_SPLASH: '#D6EAF5',
  SNOW: '#E8EDF2',
  SNOW_SPARKLE: '#FAFBFD',
  THUNDER_FLASH: '#F7DBA0',
  THUNDER_BOLT: '#F2C57C',
  FOG: '#C8D0DC',
  FOG_DENSE: '#A3AEBF',

  // Plant stages
  PLANT_SEED: '#C4A882',
  PLANT_SEED_DARK: '#A88B6A',
  PLANT_SPROUT: '#B0DCC2',
  PLANT_GROWING: '#8CC6A5',
  PLANT_MATURE: '#6BA886',
  PLANT_BLOOM_PINK: '#D4A0C0',
  PLANT_BLOOM_GOLD: '#F2C57C',
  PLANT_BLOOM_BLUE: '#7EB5D6',
  PLANT_BLOOM_WHITE: '#FAFBFD',

  // UI
  COIN_GOLD: '#F2C57C',
  COIN_SHINE: '#F7DBA0',
  WINDMILL_BLADE: '#F0F3F7',
  WINDMILL_BASE: '#C4A882',
  SPRITE_GLOW: '#E6C0D6',

  // Rarity
  RARITY_COMMON: '#A3AEBF',
  RARITY_UNCOMMON: '#8CC6A5',
  RARITY_RARE: '#7EB5D6',
  RARITY_EPIC: '#D4A0C0',
  RARITY_LEGENDARY: '#F2C57C',
} as const;

export const API = {
  BASE_URL: '',  // Set from env/config
  TIMEOUT: 10000,
  RETRY_COUNT: 3,
  RETRY_DELAY: 1000,
} as const;

export const ANIMATION = {
  // Island
  ISLAND_BOB_AMPLITUDE: 2.5,
  ISLAND_BOB_SPEED: 0.0015,
  ISLAND_BREATHE_AMPLITUDE: 1.5,
  ISLAND_BREATHE_SPEED: 0.001,

  // Plant
  PLANT_SWAY_AMPLITUDE: 1.8,
  PLANT_SWAY_SPEED: 0.002,
  PLANT_GROW_BOUNCE: 0.3,
  PLANT_SPARKLE_SPEED: 0.003,
  PLANT_SPARKLE_COUNT: 4,

  // Cloud
  CLOUD_DRIFT_SPEED: 0.2,
  CLOUD_DRIFT_VARIATION: 0.15,
  CLOUD_PARALLAX_FAR: 0.3,
  CLOUD_PARALLAX_NEAR: 0.8,

  // Windmill
  WINDMILL_BASE_SPEED: 0.015,
  WINDMILL_ACCELERATION: 0.002,

  // Coin
  COIN_PARTICLE_SPEED: 1.5,
  COIN_PARTICLE_LIFE: 1200,
  COIN_COLLECT_BURST: 8,

  // Sprite
  SPRITE_FLOAT_AMPLITUDE: 3,
  SPRITE_FLOAT_SPEED: 0.002,
  SPRITE_CATCH_SHRINK: 0.3,

  // Weather transitions
  WEATHER_FADE_DURATION: 800,
  SKY_TRANSITION_DURATION: 1500,

  // UI
  TOAST_DURATION: 2500,
  TOAST_SLIDE_DURATION: 300,
  DIALOG_FADE_DURATION: 200,
  PANEL_SLIDE_DURATION: 350,
  BUTTON_PRESS_SCALE: 0.92,
  BUTTON_RELEASE_SCALE: 1.0,
  SKELETON_SHIMMER_SPEED: 0.003,
  TAB_INDICATOR_DURATION: 250,

  // Scene transitions
  SCENE_FADE_DURATION: 400,
  SCENE_SLIDE_DURATION: 350,
} as const;

export const RARITY_COLORS: Record<string, string> = {
  common: COLORS.RARITY_COMMON,
  uncommon: COLORS.RARITY_UNCOMMON,
  rare: COLORS.RARITY_RARE,
  epic: COLORS.RARITY_EPIC,
  legendary: COLORS.RARITY_LEGENDARY,
};
